### ISSUE TITLE
http://fonts.useso.com/css?family=Source+Code+Pro这个引入非常慢怎么办?

### ISSUE THREAD

**Issue by czgaotian** [henryhuang/hexo-theme-aloha#13]
页面打开速度被这个引用严重拖慢了，
显示Status Code:502 Bad Gateway，
搜索了一下，发现这是360的公共库，已经停止服务了，
可以替换成谷歌的公共库，找不到设置的地方在哪里

**Comment by henryhuang** [comment]
@czgaotian  https://github.com/henryhuang/hexo-theme-aloha/blob/45253fc117c0bb5f9a3c7e3adef32eda71d9559f/layout/layout.ejs#L35 在这里，有时间可以改回谷歌的

**Comment by henryhuang** [comment]
@czgaotian 已经改成谷歌的了
