### ISSUE TITLE
哈喽

### ISSUE THREAD

**Issue by AustinWp** [henryhuang/hexo-theme-aloha#17]
hi,喜欢你的这个主题风格，很简约，所以使用了，但是现在有两个问题请教一下：
1、我没办法修改头像，把图片放入对应的位置，然后修改config文件并不成功。
2、如何让主题能够加上代码高亮的功能呢？修改highlight没用

**Comment by henryhuang** [comment]
@Woooop Hi，谢谢关注，
1. [https://huangyijie.com/hexo-theme-aloha/2017/09/18/How-To-Change-Avatar/](https://huangyijie.com/hexo-theme-aloha/2017/09/18/How-To-Change-Avatar/)
可能刚刚部署完还看不出效果，等一会再强制刷新一下页面，应该就可以了

1. [https://huangyijie.com/hexo-theme-aloha/2017/09/18/Code-Highlight/](https://huangyijie.com/hexo-theme-aloha/2017/09/18/Code-Highlight/)

**Comment by AustinWp** [comment]
按照你的做了，但是还是没效果，https://github.com/Woooop/MyBlog/blob/master/_config.yml 这是我的config文件

**Comment by henryhuang** [comment]
@Woooop ,你的配置没问题，我下载了你的博客源码，发现原因是你要高亮的是objective-c，它对应的高亮标示不是**objective-c**，而是**objc**，比如你那篇 **重读SDWebImage.md**，改一下就好了。

另外，我发现你的post文件名是中文，建议不要用中文；还有，我看你博客的源码 https://github.com/Woooop/MyBlog 里上传了 node_modules，这是node项目的library，不需要上传的，不然会很大，要把它加到项目根目录的 .gitignore 文件里。

**Comment by AustinWp** [comment]
OK~3qqqqq
