### ISSUE TITLE
求助~~

### ISSUE THREAD

**Issue by FurionXin** [henryhuang/hexo-theme-aloha#6]
我更改了您的样式后，之前写的文章怎么找不到了。显示不出来了。。。。。。

**Comment by henryhuang** [comment]
@FurionXin 你能说下抖改了什么内容吗？还有，文章的源 .md 或者 .markdown 还在吗？

**Comment by XuanJiAndroid** [comment]
和楼主一样，本地预览是有文章的，但是发布到服务器居然没有文章，文章的源.md还在

**Comment by henryhuang** [comment]
@XuanJiAndroid 你能看下你 原文章 所在的目录下面有没有相同名字的html文件吗？
