### ISSUE TITLE
添加评论框

### ISSUE THREAD

**Issue by lessouterrain** [henryhuang/hexo-theme-aloha#7]
你好，看到你自己使用的里面是用的多说评论，请问如何添加disqus的评论框呢？我在站点的配置文件 _config.yml 里写了disqus_shortname的变量但是生成的网页里并没有出现。是theme的配置文件里也需另外添加什么吗？
谢谢

**Comment by henryhuang** [comment]
@lessouterrain Sorry, 我还没加上这个支持，不过这个功能加上去简单，你有没有兴趣加一下？哈哈。没时间的话我加上去后给你说

**Comment by henryhuang** [comment]
@lessouterrain  添加好了 https://github.com/henryhuang/hexo-theme-aloha/wiki/zh_CN#disqus ，可以从 master pull 了。
